version: '3.8'

services:
  app01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app01
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db01

  db01:
    image: mysql:8.0
    container_name: db01
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
 